package local:app;

interface helpers-interface {
  chat-completion: func(api-key: string, json: string) -> string;
  get-balance: func(rpc: string, address: string) -> string;
}

world helpers {
  export helpers-interface;
}

world app {
  import helpers-interface;
}
