package local:app;

interface helpers-interface {
  helper-open-a-i: func(x: string) -> string;
  helper-solana: func(x: string) -> string;
}

world helpers {
  export helpers-interface;
}

world app {
  import helpers-interface;
  include wasi:http/proxy@0.2.2;
}
